### ISSUE TITLE
startMonitoringForRegion causes App to crash on new SDK

### ISSUE THREAD

**Issue by CookieCookson** [evothings/phonegap-estimotebeacons#64]
Hi, I've recently updated the plugin version on my project from 0.4~ to 0.6.0. With this I have had to update to support the new estimote.beacon calls which makes sense with the nearable additions. 

Upon testing I have discovered that if you try to start monitoring for a region whilst bluetooth is turned OFF, the App will completely crash out.

Xcode log:
-[CLBeaconRegion inMotion]: unrecognized selector sent to instance 0x1536be00
**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[CLBeaconRegion inMotion]: unrecognized selector sent to instance 0x1536be00'
**\* First throw call stack:
(0x23e7949f 0x31633c8b 0x23e7e8b9 0x23e7c7d7 0x23dae058 0x25d6a5 0x256963 0x194d0b 0x195747 0x25afe3 0x245390d5 0x24533c2b 0x2452d9a1 0x23e3fd7d 0x23e3f041 0x23e3db7b 0x23d8b3c1 0x23d8b1d3 0x2b1890a9 0x273997b1 0xfda07 0x31bb3aaf)
libc++abi.dylib: terminating with uncaught exception of type NSException

Any ideas?
## UPDATE

This also happens when updating to version 0.7.0

**Comment by CookieCookson** [comment]
I've put in a temporary fix by checking whether bluetooth is enabled before performing any beacon-based activities. (using http://plugins.cordova.io/#/package/org.chromium.bluetooth and chrome.bluetooth.getAdapterState)

**Comment by divineprog** [comment]
@CookieCookson Hi and thanks for reporting. I can confirm you findings, ranging beacons also produces this crash. This happens in the Estimote iOS Library. I will look into adding a check in the plugin that Bluetooth is turned on before starting any monitoring/ranging operations.

**Comment by divineprog** [comment]
Hi again, just pushed an update that adds a function for checking if Bluetooth is on or off: https://github.com/evothings/phonegap-estimotebeacons/commit/c7504d928413e27f9e0150826ca66fc1a19ac99a

The downside is that a dialog is presented to the user initially if Bluetooth is off. Did you experience this also with the Chromium plugin?

Did not put this check into the plugin functions yet. Would that be desirable or should we require the called to check Bluetooth state? Eventually Estimote should fix the bug with ranging crashing when Bluetooth is off.

**Comment by dylandechant** [comment]
@CookieCookson were you able to keep it from crashing if bluetooth was turned off while ranging?  I'm listening for the event but can't stop ranging fast enough...

**Comment by CookieCookson** [comment]
@dylandechant I believe it still crashes in some scenarios. Are you listening for the bluetooth turning off and then stopping ranging?

**Comment by dylandechant** [comment]
@CookieCookson yes, i listen for bluetooth to be turned off, in that event i then stop the ranging. Still get the crash.

**Comment by CookieCookson** [comment]
@dylandechant I get this issue too, might want to open a seperate issue on the repo for this.

**Comment by dylandechant** [comment]
@divineprog I don't really consider it a downside, the end user would usually want to know at some point anyways.  Any ETA on when this goes into the plugin functions?  Thanks for your help!

**Comment by CookieCookson** [comment]
@dylandechant I believe it is a massive downside as if you are literally checking if the user has bluetooth enabled to see whether you should start ranging, it tells them! I avoided this by having a pre-check to see if their intent was to allow beacon functionality first off. I could see it being useful in scenarios where the Bluetooth is required, but if you are trying to do background trickery it defeats the point.

**Comment by dylandechant** [comment]
@CookieCookson Ahhh, I agree, I think I misunderstood what @divineprog 's was outlining.  Thanks for the clarification.

**Comment by McGern** [comment]
Is there any resolution yet? I have found that if I start the monitoring well after the app has started e.g. from safari console, it seems to be fine (just going to test a workaround now). Just crashes every time after the app installed to the phone from xcode. iOS 8.1, 9.01, 9.1

**Comment by CookieCookson** [comment]
I'm not sure if anyone is actively updating this plugin which is a shame. The SDK version needs a big boost to work with beacons on newer firmware and all the other issues that have been reported. The last update was done about 3 months ago, and is running off an old SDK (3.3.1) back in July (we are now on 3.8.0).

**Comment by tavojavi** [comment]
It will be great to have a better plugin!
